### ISSUE TITLE
[Craftconomy3] Issue - Nickname Issue using Commands

### ISSUE THREAD

**Issue by afchlam** [DomeDD/BetterNick#129]
Pastebin:

https://pastebin.com/d10jz4ae

**Comment by romansorin** [comment]
It looks as if 'PlayerCallNickEvent' is referencing a null value or parameter, thus generating the null exception. Since all you provided was the error log, check that the method calling the event has passed in some value before executing the event, or have a handler which will take care of the exception.

**Comment by DomeDD** [comment]
It's the Economy plugin, I will take a look at that!

**Comment by DomeDD** [comment]
So i will update the economy hook in my plugin. But Craftconomy behaves weird on my server, everytime I nick and do /money I don't get a message but the console does... Craftconomy also doesn't get updates anymore so you should switch to another plugin maybe
